In [1]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

In [2]:
df = pd.read_csv('/content/discriptors_filtred_class_pIC50.csv')

In [3]:
X = df.drop('pIC50', axis=1)
X = X.drop('bioactivity_class', axis=1)
X

PubchemFP0  PubchemFP1  PubchemFP2  PubchemFP3  PubchemFP4  PubchemFP5  \
0              1           1           1           0           0           0   
1              1           1           1           0           0           0   
2              1           1           0           0           0           0   
3              1           1           0           0           0           0   
4              1           1           1           0           0           0   
...          ...         ...         ...         ...         ...         ...   
3618           1           1           1           0           0           0   
3619           1           1           1           0           0           0   
3620           1           1           1           0           0           0   
3621           1           1           1           1           0           0   
3622           1           1           1           0           0           0   

      PubchemFP6  PubchemFP7  PubchemFP8  PubchemFP9  ...  PubchemFP871  \
0              0           0           0           1  ...             0   
1              0           0           0           1  ...             0   
2              0           0           0           1  ...             0   
3              0           0           0           1  ...             0   
4              0           0           0           1  ...             0   
...          ...         ...         ...         ...  ...           ...   
3618           0           0           0           1  ...             0   
3619           0           0           0           1  ...             0   
3620           0           0           0           1  ...             0   
3621           0           0           0           1  ...             0   
3622           0           0           0           1  ...             0   

      PubchemFP872  PubchemFP873  PubchemFP874  PubchemFP875  PubchemFP876  \
0                0             0             0             0             0   
1                0             0             0             0             0   
2                0             0             0             0             0   
3                0             0             0             0             0   
4                0             0             0             0             0   
...            ...           ...           ...           ...           ...   
3618             0             0             0             0             0   
3619             0             0             0             0             0   
3620             0             0             0             0             0   
3621             0             0             0             0             0   
3622             0             0             0             0             0   

      PubchemFP877  PubchemFP878  PubchemFP879  PubchemFP880  
0                0             0             0             0  
1                0             0             0             0  
2                0             0             0             0  
3                0             0             0             0  
4                0             0             0             0  
...            ...           ...           ...           ...  
3618             0             0             0             0  
3619             0             0             0             0  
3620             0             0             0             0  
3621             0             0             0             0  
3622             0             0             0             0  

[3623 rows x 881 columns]

In [4]:
train = df.drop('pIC50', axis=1)
train

PubchemFP0  PubchemFP1  PubchemFP2  PubchemFP3  PubchemFP4  PubchemFP5  \
0              1           1           1           0           0           0   
1              1           1           1           0           0           0   
2              1           1           0           0           0           0   
3              1           1           0           0           0           0   
4              1           1           1           0           0           0   
...          ...         ...         ...         ...         ...         ...   
3618           1           1           1           0           0           0   
3619           1           1           1           0           0           0   
3620           1           1           1           0           0           0   
3621           1           1           1           1           0           0   
3622           1           1           1           0           0           0   

      PubchemFP6  PubchemFP7  PubchemFP8  PubchemFP9  ...  PubchemFP872  \
0              0           0           0           1  ...             0   
1              0           0           0           1  ...             0   
2              0           0           0           1  ...             0   
3              0           0           0           1  ...             0   
4              0           0           0           1  ...             0   
...          ...         ...         ...         ...  ...           ...   
3618           0           0           0           1  ...             0   
3619           0           0           0           1  ...             0   
3620           0           0           0           1  ...             0   
3621           0           0           0           1  ...             0   
3622           0           0           0           1  ...             0   

      PubchemFP873  PubchemFP874  PubchemFP875  PubchemFP876  PubchemFP877  \
0                0             0             0             0             0   
1                0             0             0             0             0   
2                0             0             0             0             0   
3                0             0             0             0             0   
4                0             0             0             0             0   
...            ...           ...           ...           ...           ...   
3618             0             0             0             0             0   
3619             0             0             0             0             0   
3620             0             0             0             0             0   
3621             0             0             0             0             0   
3622             0             0             0             0             0   

      PubchemFP878  PubchemFP879  PubchemFP880  bioactivity_class  
0                0             0             0             active  
1                0             0             0             active  
2                0             0             0             active  
3                0             0             0             active  
4                0             0             0             active  
...            ...           ...           ...                ...  
3618             0             0             0             active  
3619             0             0             0             active  
3620             0             0             0             active  
3621             0             0             0           inactive  
3622             0             0             0             active  

[3623 rows x 882 columns]

In [9]:
Y = df.bioactivity_class
Y

0         active
1         active
2         active
3         active
4         active
          ...   
3618      active
3619      active
3620      active
3621    inactive
3622      active
Name: bioactivity_class, Length: 3623, dtype: object

In [10]:
Y = [1 if c == "active" else 0 for c in Y]


In [11]:
Y = pd.core.series.Series(Y)

In [12]:
X.shape

(3623, 881)

In [13]:
Y.shape

(3623,)

In [14]:
import numpy as np

In [15]:
type(Y)

pandas.core.series.Series

In [16]:
Y.shape

(3623,)

In [17]:
#from sklearn.feature_selection import VarianceThreshold
#selection = VarianceThreshold(threshold=(.8 * (1 - .8)))    
#X = selection.fit_transform(X)

In [18]:
X.shape

(3623, 881)

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [20]:
type(X_test)

pandas.core.frame.DataFrame

In [21]:
X_train.shape, Y_train.shape

((2898, 881), (2898,))

In [22]:
X_test.shape, Y_test.shape

((725, 881), (725,))

#Machine learning

In [24]:
from sklearn.tree import DecisionTreeRegressor, ExtraTreeRegressor

from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import scale
import matplotlib.pyplot as plt
from sklearn import set_config 

In [36]:
from sklearn.tree import ExtraTreeClassifier, DecisionTreeClassifier

In [25]:
! pip install lazypredict

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [27]:
import lazypredict
from lazypredict.Supervised import LazyClassifier

In [28]:
# Defines and builds the lazyclassifier
clf = LazyClassifier(verbose=0,ignore_warnings=True, custom_metric=None)
models_train,classifier_train = clf.fit(X_train, X_train, Y_train, Y_train)
models_test,classifier_test = clf.fit(X_train, X_test, Y_train, Y_test)

100%|██████████| 29/29 [01:10<00:00,  2.43s/it]


'tuple' object has no attribute '__name__'
Invalid Classifier(s)


100%|██████████| 29/29 [00:59<00:00,  2.07s/it]


In [29]:
classifier_train

Accuracy  Balanced Accuracy  ROC AUC  F1 Score  \
Model                                                                           
DecisionTreeClassifier             0.98               0.98     0.98      0.98   
ExtraTreeClassifier                0.98               0.98     0.98      0.98   
ExtraTreesClassifier               0.98               0.98     0.98      0.98   
LabelPropagation                   0.98               0.98     0.98      0.98   
LabelSpreading                     0.98               0.98     0.98      0.98   
RandomForestClassifier             0.98               0.98     0.98      0.98   
BaggingClassifier                  0.97               0.97     0.97      0.97   
XGBClassifier                      0.95               0.94     0.94      0.95   
LGBMClassifier                     0.91               0.90     0.90      0.91   
NuSVC                              0.87               0.85     0.85      0.87   
SVC                                0.84               0.82     0.82      0.84   
KNeighborsClassifier               0.83               0.81     0.81      0.83   
LinearDiscriminantAnalysis         0.83               0.81     0.81      0.83   
RidgeClassifier                    0.83               0.81     0.81      0.83   
LinearSVC                          0.83               0.81     0.81      0.82   
LogisticRegression                 0.83               0.81     0.81      0.83   
RidgeClassifierCV                  0.83               0.81     0.81      0.82   
SGDClassifier                      0.78               0.75     0.75      0.78   
CalibratedClassifierCV             0.80               0.75     0.75      0.79   
Perceptron                         0.73               0.73     0.73      0.74   
PassiveAggressiveClassifier        0.73               0.72     0.72      0.73   
AdaBoostClassifier                 0.74               0.70     0.70      0.73   
NearestCentroid                    0.69               0.67     0.67      0.69   
BernoulliNB                        0.69               0.66     0.66      0.68   
QuadraticDiscriminantAnalysis      0.57               0.66     0.66      0.54   
GaussianNB                         0.41               0.53     0.53      0.28   
DummyClassifier                    0.62               0.50     0.50      0.48   

                               Time Taken  
Model                                      
DecisionTreeClassifier               0.29  
ExtraTreeClassifier                  0.17  
ExtraTreesClassifier                 1.49  
LabelPropagation                     2.18  
LabelSpreading                       1.85  
RandomForestClassifier               1.91  
BaggingClassifier                    1.20  
XGBClassifier                       12.11  
LGBMClassifier                       0.64  
NuSVC                                6.90  
SVC                                  6.78  
KNeighborsClassifier                 0.71  
LinearDiscriminantAnalysis           1.47  
RidgeClassifier                      0.36  
LinearSVC                            5.20  
LogisticRegression                   0.48  
RidgeClassifierCV                    1.42  
SGDClassifier                        0.68  
CalibratedClassifierCV              18.14  
Perceptron                           0.27  
PassiveAggressiveClassifier          0.34  
AdaBoostClassifier                   3.09  
NearestCentroid                      0.21  
BernoulliNB                          0.26  
QuadraticDiscriminantAnalysis        1.84  
GaussianNB                           0.22  
DummyClassifier                      0.14

##ExtraTreeClassifier

In [31]:
model = ExtraTreeClassifier()
model.fit(X_train, Y_train)
r2 = model.score(X_test, Y_test)
r2

0.7558620689655172

In [32]:
Y_pred = model.predict(X_test)

In [34]:
Y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,

In [35]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

Ytest = Y_test
rounded = Y_pred

# Calculer la matrice de confusion
confusion = confusion_matrix(Ytest, rounded)
print("Matrice de confusion :")
print(confusion)

# Calculer l'exactitude (accuracy) du modèle
accuracy = accuracy_score(Ytest, rounded)
print("Accuracy score : {:.2f}".format(accuracy))

# Calculer la précision (precision) du modèle
precision = precision_score(Ytest, rounded)
print("Précision : {:.2f}".format(precision))

# Calculer le rappel (recall) du modèle
recall = recall_score(Ytest, rounded)
print("Recall score : {:.2f}".format(recall))

# Calculer la F-mesure (F1-score) du modèle
f1 = f1_score(Ytest, rounded)
print("F-mesure : {:.2f}".format(f1))


Matrice de confusion :
[[188  76]
 [101 360]]
Accuracy score : 0.76
Précision : 0.83
Recall score : 0.78
F-mesure : 0.80


##DecisionTreeClassifier

In [37]:
model = DecisionTreeClassifier()
model.fit(X_train, Y_train)
r2 = model.score(X_test, Y_test)
r2

0.7627586206896552

In [38]:
Y_pred = model.predict(X_test)

In [39]:
Y_pred

array([0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,

In [40]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

Ytest = Y_test
rounded = Y_pred

# Calculer la matrice de confusion
confusion = confusion_matrix(Ytest, rounded)
print("Matrice de confusion :")
print(confusion)

# Calculer l'exactitude (accuracy) du modèle
accuracy = accuracy_score(Ytest, rounded)
print("Accuracy score : {:.2f}".format(accuracy))

# Calculer la précision (precision) du modèle
precision = precision_score(Ytest, rounded)
print("Précision : {:.2f}".format(precision))

# Calculer le rappel (recall) du modèle
recall = recall_score(Ytest, rounded)
print("Recall score : {:.2f}".format(recall))

# Calculer la F-mesure (F1-score) du modèle
f1 = f1_score(Ytest, rounded)
print("F-mesure : {:.2f}".format(f1))


Matrice de confusion :
[[197  67]
 [105 356]]
Accuracy score : 0.76
Précision : 0.84
Recall score : 0.77
F-mesure : 0.81
